--
-- PostgreSQL database dump
--

\restrict GZlam1W4PGQfohhK4wZj1I5w4MtfXJheUNYgltBF6UOvQfOuaoN2CC11F1mUJPJ

-- Dumped from database version 13.22 (Debian 13.22-1.pgdg13+1)
-- Dumped by pg_dump version 13.22 (Debian 13.22-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO hello;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO hello;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO hello;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO hello;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO hello;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO hello;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO hello;

--
-- Name: warehouse_item; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_item (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    sku character varying(100) NOT NULL,
    description text,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    location_id bigint
);


ALTER TABLE public.warehouse_item OWNER TO hello;

--
-- Name: warehouse_item_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_location; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_location (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    code character varying(50) NOT NULL,
    description text
);


ALTER TABLE public.warehouse_location OWNER TO hello;

--
-- Name: warehouse_location_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_movement; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_movement (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    movement_type character varying(50) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    item_id bigint NOT NULL,
    performed_by_id bigint
);


ALTER TABLE public.warehouse_movement OWNER TO hello;

--
-- Name: warehouse_movement_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_movement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_order; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_order (
    id bigint NOT NULL,
    order_type character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    supplier_id bigint
);


ALTER TABLE public.warehouse_order OWNER TO hello;

--
-- Name: warehouse_order_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_orderitem; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    item_id bigint NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.warehouse_orderitem OWNER TO hello;

--
-- Name: warehouse_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_supplier; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_supplier (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    contact_info character varying(255),
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.warehouse_supplier OWNER TO hello;

--
-- Name: warehouse_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_user; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(50) NOT NULL
);


ALTER TABLE public.warehouse_user OWNER TO hello;

--
-- Name: warehouse_user_groups; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.warehouse_user_groups OWNER TO hello;

--
-- Name: warehouse_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_user_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_user_user_permissions; Type: TABLE; Schema: public; Owner: hello
--

CREATE TABLE public.warehouse_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.warehouse_user_user_permissions OWNER TO hello;

--
-- Name: warehouse_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: hello
--

ALTER TABLE public.warehouse_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: warehouse_item warehouse_item_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_item
    ADD CONSTRAINT warehouse_item_pkey PRIMARY KEY (id);


--
-- Name: warehouse_item warehouse_item_sku_key; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_item
    ADD CONSTRAINT warehouse_item_sku_key UNIQUE (sku);


--
-- Name: warehouse_location warehouse_location_code_key; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_location
    ADD CONSTRAINT warehouse_location_code_key UNIQUE (code);


--
-- Name: warehouse_location warehouse_location_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_location
    ADD CONSTRAINT warehouse_location_pkey PRIMARY KEY (id);


--
-- Name: warehouse_movement warehouse_movement_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_pkey PRIMARY KEY (id);


--
-- Name: warehouse_order warehouse_order_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_order
    ADD CONSTRAINT warehouse_order_pkey PRIMARY KEY (id);


--
-- Name: warehouse_orderitem warehouse_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_orderitem
    ADD CONSTRAINT warehouse_orderitem_pkey PRIMARY KEY (id);


--
-- Name: warehouse_supplier warehouse_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_supplier
    ADD CONSTRAINT warehouse_supplier_pkey PRIMARY KEY (id);


--
-- Name: warehouse_user_groups warehouse_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_groups
    ADD CONSTRAINT warehouse_user_groups_pkey PRIMARY KEY (id);


--
-- Name: warehouse_user_groups warehouse_user_groups_user_id_group_id_2e1e6872_uniq; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_groups
    ADD CONSTRAINT warehouse_user_groups_user_id_group_id_2e1e6872_uniq UNIQUE (user_id, group_id);


--
-- Name: warehouse_user warehouse_user_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user
    ADD CONSTRAINT warehouse_user_pkey PRIMARY KEY (id);


--
-- Name: warehouse_user_user_permissions warehouse_user_user_perm_user_id_permission_id_09a0c368_uniq; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_user_permissions
    ADD CONSTRAINT warehouse_user_user_perm_user_id_permission_id_09a0c368_uniq UNIQUE (user_id, permission_id);


--
-- Name: warehouse_user_user_permissions warehouse_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_user_permissions
    ADD CONSTRAINT warehouse_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: warehouse_user warehouse_user_username_key; Type: CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user
    ADD CONSTRAINT warehouse_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: warehouse_item_created_by_id_bc89e43b; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_item_created_by_id_bc89e43b ON public.warehouse_item USING btree (created_by_id);


--
-- Name: warehouse_item_location_id_bb2c4366; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_item_location_id_bb2c4366 ON public.warehouse_item USING btree (location_id);


--
-- Name: warehouse_item_sku_903c23e9_like; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_item_sku_903c23e9_like ON public.warehouse_item USING btree (sku varchar_pattern_ops);


--
-- Name: warehouse_location_code_99e78d59_like; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_location_code_99e78d59_like ON public.warehouse_location USING btree (code varchar_pattern_ops);


--
-- Name: warehouse_movement_item_id_b97fbab5; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_movement_item_id_b97fbab5 ON public.warehouse_movement USING btree (item_id);


--
-- Name: warehouse_movement_performed_by_id_6f70292f; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_movement_performed_by_id_6f70292f ON public.warehouse_movement USING btree (performed_by_id);


--
-- Name: warehouse_order_created_by_id_2f12c27f; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_order_created_by_id_2f12c27f ON public.warehouse_order USING btree (created_by_id);


--
-- Name: warehouse_order_supplier_id_751ebd82; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_order_supplier_id_751ebd82 ON public.warehouse_order USING btree (supplier_id);


--
-- Name: warehouse_orderitem_item_id_9caa43d1; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_orderitem_item_id_9caa43d1 ON public.warehouse_orderitem USING btree (item_id);


--
-- Name: warehouse_orderitem_order_id_d84c2257; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_orderitem_order_id_d84c2257 ON public.warehouse_orderitem USING btree (order_id);


--
-- Name: warehouse_user_groups_group_id_1f6af024; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_user_groups_group_id_1f6af024 ON public.warehouse_user_groups USING btree (group_id);


--
-- Name: warehouse_user_groups_user_id_4e0104d5; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_user_groups_user_id_4e0104d5 ON public.warehouse_user_groups USING btree (user_id);


--
-- Name: warehouse_user_user_permissions_permission_id_574e6018; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_user_user_permissions_permission_id_574e6018 ON public.warehouse_user_user_permissions USING btree (permission_id);


--
-- Name: warehouse_user_user_permissions_user_id_e8a8e8da; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_user_user_permissions_user_id_e8a8e8da ON public.warehouse_user_user_permissions USING btree (user_id);


--
-- Name: warehouse_user_username_96cbfe7b_like; Type: INDEX; Schema: public; Owner: hello
--

CREATE INDEX warehouse_user_username_96cbfe7b_like ON public.warehouse_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_warehouse_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_warehouse_user_id FOREIGN KEY (user_id) REFERENCES public.warehouse_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_item warehouse_item_created_by_id_bc89e43b_fk_warehouse_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_item
    ADD CONSTRAINT warehouse_item_created_by_id_bc89e43b_fk_warehouse_user_id FOREIGN KEY (created_by_id) REFERENCES public.warehouse_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_item warehouse_item_location_id_bb2c4366_fk_warehouse_location_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_item
    ADD CONSTRAINT warehouse_item_location_id_bb2c4366_fk_warehouse_location_id FOREIGN KEY (location_id) REFERENCES public.warehouse_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_movement warehouse_movement_item_id_b97fbab5_fk_warehouse_item_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_item_id_b97fbab5_fk_warehouse_item_id FOREIGN KEY (item_id) REFERENCES public.warehouse_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_movement warehouse_movement_performed_by_id_6f70292f_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_performed_by_id_6f70292f_fk_warehouse FOREIGN KEY (performed_by_id) REFERENCES public.warehouse_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_order warehouse_order_created_by_id_2f12c27f_fk_warehouse_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_order
    ADD CONSTRAINT warehouse_order_created_by_id_2f12c27f_fk_warehouse_user_id FOREIGN KEY (created_by_id) REFERENCES public.warehouse_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_order warehouse_order_supplier_id_751ebd82_fk_warehouse_supplier_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_order
    ADD CONSTRAINT warehouse_order_supplier_id_751ebd82_fk_warehouse_supplier_id FOREIGN KEY (supplier_id) REFERENCES public.warehouse_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_orderitem warehouse_orderitem_item_id_9caa43d1_fk_warehouse_item_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_orderitem
    ADD CONSTRAINT warehouse_orderitem_item_id_9caa43d1_fk_warehouse_item_id FOREIGN KEY (item_id) REFERENCES public.warehouse_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_orderitem warehouse_orderitem_order_id_d84c2257_fk_warehouse_order_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_orderitem
    ADD CONSTRAINT warehouse_orderitem_order_id_d84c2257_fk_warehouse_order_id FOREIGN KEY (order_id) REFERENCES public.warehouse_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_user_groups warehouse_user_groups_group_id_1f6af024_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_groups
    ADD CONSTRAINT warehouse_user_groups_group_id_1f6af024_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_user_groups warehouse_user_groups_user_id_4e0104d5_fk_warehouse_user_id; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_groups
    ADD CONSTRAINT warehouse_user_groups_user_id_4e0104d5_fk_warehouse_user_id FOREIGN KEY (user_id) REFERENCES public.warehouse_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_user_user_permissions warehouse_user_user__permission_id_574e6018_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_user_permissions
    ADD CONSTRAINT warehouse_user_user__permission_id_574e6018_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: warehouse_user_user_permissions warehouse_user_user__user_id_e8a8e8da_fk_warehouse; Type: FK CONSTRAINT; Schema: public; Owner: hello
--

ALTER TABLE ONLY public.warehouse_user_user_permissions
    ADD CONSTRAINT warehouse_user_user__user_id_e8a8e8da_fk_warehouse FOREIGN KEY (user_id) REFERENCES public.warehouse_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict GZlam1W4PGQfohhK4wZj1I5w4MtfXJheUNYgltBF6UOvQfOuaoN2CC11F1mUJPJ

